# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azctx < Formula
  desc "Switch faster between subscriptions in your azure cli."
  homepage "https://githubs.com/StiviiK/azctx"
  version "1.0-beta8"
  license "MIT"

  depends_on "azure-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StiviiK/azctx/releases/download/v1.0-beta8/azctx_darwin_amd64.zip"
      sha256 "78dc3a1fca6d7924f0d5b391fe9eac09152556d552c81390317f3dc995e53111"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StiviiK/azctx/releases/download/v1.0-beta8/azctx_darwin_arm64.zip"
      sha256 "778d40ddff7dd74559cc3f380f4afa7a930c78679dd0c597ff214f9cb99b74a3"

      def install
        bin.install "azctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/StiviiK/azctx/releases/download/v1.0-beta8/azctx_linux_armv6.zip"
      sha256 "88c396d27c1d1e1dff74ffbedfd808e4ed618f89b009edbb6948ef1c104615c1"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/StiviiK/azctx/releases/download/v1.0-beta8/azctx_linux_amd64.zip"
      sha256 "66a82f174f9f676fb5ef73c6584595ad6dca97469bdf0b92e960aaa7a0070658"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StiviiK/azctx/releases/download/v1.0-beta8/azctx_linux_arm64.zip"
      sha256 "1ba7d985e18e3c22467c683a4359d11182c206aea75b0c6c80bded8b83a2db0e"

      def install
        bin.install "azctx"
      end
    end
  end
end
