# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azctx < Formula
  desc "Switch faster between subscriptions in your azure cli."
  homepage "https://githubs.com/StiviiK/azctx"
  version "2023.04.2"
  license "MIT"

  depends_on "azure-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/StiviiK/azctx/releases/download/2023.04.2/azctx_darwin_arm64.zip"
      sha256 "d38b347f0a5786302ef94870bb095b07bf9004c1ecf2ebd6023148369c65ab55"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/StiviiK/azctx/releases/download/2023.04.2/azctx_darwin_amd64.zip"
      sha256 "aeaacf21469725643fd63413bef60ef8d35f104843f8d6503a9054b560880833"

      def install
        bin.install "azctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/StiviiK/azctx/releases/download/2023.04.2/azctx_linux_armv6.zip"
      sha256 "91d62fc63f84f4ae72bfe3e0c5844ac1e91176cdbbca4424e39edfa1eff63597"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/StiviiK/azctx/releases/download/2023.04.2/azctx_linux_amd64.zip"
      sha256 "efdd7afda5ca39b3f5ddbe74c0ca20af8cde84b025c69c3d3d1e59fbd36a345b"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StiviiK/azctx/releases/download/2023.04.2/azctx_linux_arm64.zip"
      sha256 "9a9cb754df3270840360fc4488155172162a3f19d51cff6e121d54a9470edbfb"

      def install
        bin.install "azctx"
      end
    end
  end
end
